FROM node:10

WORKDIR /app

COPY frontend /app/frontend
RUN cd frontend && yarn install
RUN cd frontend && yarn build

FROM golang:1.14.0-alpine3.11

WORKDIR /app
COPY / /app/
COPY --from=0 /app/frontend/build /app/frontend/build

RUN go get github.com/rakyll/statik
RUN statik -f -src=./frontend/build -dest=server/ -p public
RUN go build -tags release -o skydive-visualizer